ALTER TABLE promotions
  ADD COLUMN IF NOT EXISTS source_month INTEGER,
  ADD COLUMN IF NOT EXISTS source_year INTEGER,
  ADD COLUMN IF NOT EXISTS target_month INTEGER,
  ADD COLUMN IF NOT EXISTS target_year INTEGER;
